In [50]:
#Question 12 Page570  #Chisquare test of association
import pandas as pd
import numpy as np
import scipy.stats as stats
from scipy.stats import chi2_contingency

In [51]:
df=pd.read_excel("C:/Users/asus/Desktop/SMDA solved/PythonStatistics - SMDA/Q12.xlsx")
df

Company    Hiring
0    Private       Add
1    Private       Add
2    Private       Add
3    Private       Add
4    Private       Add
..       ...       ...
175   Public  nochange
176   Public  nochange
177   Public  nochange
178   Public  nochange
179   Public  nochange

[180 rows x 2 columns]

In [52]:
#Ho: The hiring plan and company type are independent
#Ha:The hirng plan and company type are dependent
pd.crosstab(df.Company, df.Hiring, margins=True)

Hiring   Add  Layoff  nochange  All
Company                            
Private   37      16        19   72
Public    32      42        34  108
All       69      58        53  180

In [53]:
chi2_stat,p_value,dof,ex=stats.chi2_contingency(pd.crosstab(df.Hiring,df.Company)) #here ex stands for expected frequency

In [54]:
print("chisq_stat=:",chi2_stat)
print("degrees_of_freedom=:",dof)
print("p_value=:",p_value)
print("contingency_table:")
print(ex)

chisq_stat=: 9.440389867959102
degrees_of_freedom=: 2
p_value=: 0.008913440846580769
contingency_table:
[[27.6 41.4]
 [23.2 34.8]
 [21.2 31.8]]


In [55]:
alpha=0.05
if p_value>alpha:
    print("Fail to reject Ho")
    print("The hiring plan and company type are independent")
else:
    print("Reject Ho")
    print("The hirng plan and company type are dependent")

Reject Ho
The hirng plan and company type are dependent


In [56]:
#Question 14 Page571 
import pandas as pd
import numpy as np
import scipy.stats as stats
from scipy.stats import chi2_contingency

In [57]:
df=pd.read_excel("C:/Users/asus/Desktop/SMDA solved/PythonStatistics - SMDA/autoquality.xlsx")
df

Rating     Education
0        Average  College Grad
1    Outstanding       HS Grad
2        Average  Some College
3    Outstanding  College Grad
4    Exceptional  College Grad
..           ...           ...
495      Average       HS Grad
496  Outstanding       HS Grad
497  Exceptional  College Grad
498  Outstanding  Some College
499  Exceptional  Some College

[500 rows x 2 columns]

In [58]:
#Ho: The Ratings and Education are independent
#Ha: The Ratings and Education are dependent
pd.crosstab(df.Rating, df.Education, margins=True)

Education    College Grad  HS Grad  Some College  Some HS  All
Rating                                                        
Average                60       30            20       35  145
Exceptional            50       25            30       20  125
Outstanding            90       45            50       45  230
All                   200      100           100      100  500

In [59]:
chi2_stat,p_value,dof,ex=stats.chi2_contingency(pd.crosstab(df.Rating,df.Education))

In [60]:
print("chisq_stat=:",chi2_stat)
print("degrees_of_freedom=:",dof)
print("p_value=:",p_value)
print("contingency_table:")
print(ex)

chisq_stat=: 6.57271364317841
degrees_of_freedom=: 6
p_value=: 0.3621737706414952
contingency_table:
[[58. 29. 29. 29.]
 [50. 25. 25. 25.]
 [92. 46. 46. 46.]]


In [61]:
alpha=0.05
if p_value>alpha:
    print("Fail to reject Ho")
    print("The Ratings and Education are independent")
else:
    print("Reject Ho")
    print("The Ratings and Education are dependent")

Fail to reject Ho
The Ratings and Education are independent
