In [1]:
#Question 17 page-388
import numpy as np
import pandas as pd
import scipy.stats as scipy
from scipy.stats import t

In [3]:
df=pd.read_csv("C:/Users/asus/Desktop/SMDA solved/PythonStatistics - SMDA//miami.csv")
df

Rating
0        6
1        4
2        6
3        8
4        7
5        7
6        6
7        3
8        3
9        8
10      10
11       4
12       8
13       7
14       8
15       7
16       5
17       9
18       5
19       8
20       4
21       3
22       8
23       5
24       5
25       4
26       4
27       4
28       8
29       4
30       5
31       6
32       2
33       5
34       9
35       9
36       8
37       4
38       8
39       9
40       9
41       5
42       9
43       7
44       8
45       3
46      10
47       8
48       9
49       6

In [7]:
df.mean()

Rating    6.34
dtype: float64

In [9]:
df.std()

Rating    2.162859
dtype: float64

In [11]:
n=50

In [13]:
standard_error=df.std()/(n**0.5)
standard_error

Rating    0.305874
dtype: float64

In [15]:
confidence_level=0.95
degree_freedom=n-1
degree_freedom
tcri=t.ppf((1+confidence_level)/2,degree_freedom)
tcri

2.0095752371292397

In [17]:
margin_error=standard_error*tcri
margin_error

Rating    0.614678
dtype: float64

In [19]:
lower_bound=df.mean()-margin_error
upper_bound=df.mean()+margin_error
confidence_interval=np.array([lower_bound,upper_bound])
confidence_interval

array([[5.72532226],
       [6.95467774]])

In [21]:
# Question 20 page 389
import numpy as np
import pandas as pd
import scipy.stats as scipy
from scipy.stats import t

In [23]:
df=pd.read_csv("C:/Users/asus/Desktop/SMDA solved/PythonStatistics - SMDA/autoinsurance.csv")
df

Annual Premium
0             1905
1             2725
2             2677
3             2600
4             2962
5             2184
6             2332
7             3112
8             2545
9             2525
10            2370
11            2545
12            2529
13            2442
14            2312
15            2981
16            2627
17            2857
18            2675
19            2115

In [25]:
df.mean()

Annual Premium    2551.0
dtype: float64

In [27]:
df.std()

Annual Premium    301.307676
dtype: float64

In [31]:
n=20

In [33]:
standard_error=df.std()/(n**0.5)
standard_error

Annual Premium    67.374445
dtype: float64

In [35]:
confidence_level=0.95
degree_freedom=n-1
degree_freedom
tcri=t.ppf((1+confidence_level)/2,degree_freedom)
tcri

2.093024054408263

In [37]:
margin_error=standard_error*tcri
margin_error

Annual Premium    141.016333
dtype: float64

In [39]:
lower_bound=df.mean()-margin_error
upper_bound=df.mean()+margin_error
confidence_interval=np.array([lower_bound,upper_bound])
confidence_interval

array([[2409.98366673],
       [2692.01633327]])

In [41]:
import numpy as np
import pandas as pd
import scipy.stats as scipy
from scipy.stats import t
from scipy.stats import norm

In [43]:
confidence_level=0.95
zcri=norm.ppf((1+confidence_level)/2)
zcri

1.959963984540054

In [45]:
n=(zcri**2*6.84**2)/(1.5**2)
n=np.round(n)
n

80.0

In [47]:
import numpy as np
import pandas as pd
import scipy.stats as scipy
from scipy.stats import t
from scipy.stats import norm

In [49]:
confidence_level=0.90
zcri=norm.ppf((1+confidence_level)/2)
zcri

1.6448536269514722

In [51]:
n=(zcri**2*25**2)/(3**2)
n=np.round(n)
n

188.0

In [53]:
confidence_level=0.95
zcri=norm.ppf((1+confidence_level)/2)
zcri

1.959963984540054

In [55]:
n=(zcri**2*25**2)/(3**2)
n=np.round(n)
n

267.0

In [57]:
confidence_level=0.99
zcri=norm.ppf((1+confidence_level)/2)
zcri

2.5758293035489004

In [59]:
n=(zcri**2*25**2)/(3**2)
n=np.round(n)
n

461.0

In [61]:
import numpy as np
import pandas as pd
import scipy.stats as scipy
from scipy.stats import t
from scipy.stats import norm

In [63]:
x=46
n=200
pcap=x/n
pcap

0.23

In [65]:
qcap=1-pcap
standard_error=((pcap*qcap)/n)**0.5
standard_error

0.02975735203273302

In [67]:
confidence_level=0.95
zcri=norm.ppf((1+confidence_level)/2)
zcri

1.959963984540054

In [69]:
moe=standard_error*zcri
moe

0.05832333825943648

In [71]:
lower_bound=pcap-moe
upper_bound=pcap+moe
confidence_interval=np.array([lower_bound,upper_bound])
confidence_interval

array([0.17167666, 0.28832334])

In [73]:
#Question 38 page- 397
import numpy as np
import pandas as pd
import scipy.stats as scipy
from scipy.stats import t
from scipy.stats import norm

In [85]:
df=pd.read_csv("C:/Users/asus/Desktop/SMDA solved/PythonStatistics - SMDA/casualdining.csv")
df

50000
0     Yes
1      No
2     Yes
3      No
4      No
..    ...
137   Yes
138    No
139    No
140   Yes
141   Yes

[142 rows x 1 columns]

In [87]:
df.head()


50000
0   Yes
1    No
2   Yes
3    No
4    No

In [89]:
obs=df['50000'].value_counts()
obs

50000
No     81
Yes    61
Name: count, dtype: int64

In [91]:
x=81
n=142
pcap=x/n
pcap

0.5704225352112676

In [93]:
qcap=1-pcap
standard_error=((pcap*qcap)/n)**0.5
standard_error

0.04154080520068493

In [95]:
confidence_level=0.95
zcri=norm.ppf((1+confidence_level)/2)
zcri

1.959963984540054

In [97]:
moe=standard_error*zcri
moe

0.08141848208213663

In [99]:
lower_bound=pcap-moe
upper_bound=pcap+moe
confidence_interval=np.array([lower_bound,upper_bound])
confidence_interval

array([0.48900405, 0.65184102])