In [18]:
import numpy as np
import pandas as pd
import scipy.stats as stat
from scipy.stats import norm 


In [22]:
#Question No 5 (Page-380) 
houston=pd.read_csv("C:/Users/asus/Desktop/DEVP/Statistics - SMDA/houston.csv")

In [24]:
houston

Amount
0    20.50
1    14.63
2    23.77
3    29.96
4    29.49
..     ...
59   15.61
60   26.46
61   24.24
62   16.66
63   20.85

[64 rows x 1 columns]

In [26]:
sample_mean=houston.mean()
sample_mean

Amount    21.52
dtype: float64

In [28]:
n=len(houston)
n
#if in case sample size is not given in the ques

64

In [32]:
sigma=6
standard_error=sigma/(n**0.5)
standard_error 
#in python raise to the power is denoted by '**'

0.75

In [36]:
#set the desired level of confidence
confidence_level=0.99
#calculate the z-score corresponding to confidence level
z_score=norm.ppf((1+confidence_level)/2)
z_score

2.5758293035489004

In [40]:
margin_of_error=z_score*standard_error
margin_of_error
#from formula of mean

1.9318719776616753

In [42]:
#Confidence interval
lower_bound=sample_mean-margin_of_error
upper_bound=sample_mean+margin_of_error
confidence_interval=np.array([lower_bound,upper_bound])
confidence_interval

array([[19.58812802],
       [23.45187198]])

In [44]:
CI=np.round(confidence_interval,decimals=2)
print(CI)

[[19.59]
 [23.45]]


In [54]:
#Question No 7 (Page-380)
setters=pd.read_csv("C:/Users/asus/Desktop/DEVP/Statistics - SMDA/setters.csv")


In [56]:
setters


Cost ($)
0       1902
1       2042
2       1936
3       1817
4       1504
5       1572
6       1532
7       1907
8       1882
9       2153
10      1945
11      1335
12      2006
13      1516
14      1839
15      1739
16      1456
17      1958
18      1934
19      2094
20      1739
21      1434
22      1667
23      1679
24      1736
25      1670
26      1770
27      2052
28      1379
29      1939
30      1854
31      1913
32      2163
33      1737
34      1888
35      1737
36      2230
37      2131
38      1813
39      2118
40      1978
41      2166
42      1482
43      1700
44      1679
45      2060
46      1683
47      1850
48      2232
49      2294

In [58]:
sample_mean=setters.mean()
sample_mean

Cost ($)    1836.84
dtype: float64

In [60]:
n=len(setters)
n

50

In [62]:
sigma=255
standard_error=sigma/(n**0.5)
standard_error 

36.062445840513924

In [64]:
confidence_level=0.95
z_score=norm.ppf((1+confidence_level)/2)
z_score

1.959963984540054

In [66]:
margin_of_error=z_score*standard_error
margin_of_error

70.68109504183357

In [68]:
lower_bound=sample_mean-margin_of_error
upper_bound=sample_mean+margin_of_error
confidence_interval=np.array([lower_bound,upper_bound])
confidence_interval

array([[1766.15890496],
       [1907.52109504]])

In [70]:
CI=np.round(confidence_interval,decimals=2)
print(CI)

[[1766.16]
 [1907.52]]
