In [13]:
#Question-10 (Page-380)
import numpy as np
import pandas as pd
import scipy.stats as stat
from scipy.stats import norm 


In [14]:
sample=120
sigma=650
standard_error=sigma/(sample**0.5)
standard_error 
#Given n=120

59.33661039639299

In [15]:
#Part-(a) 
confidence_level=0.90
z_score=norm.ppf((1+confidence_level)/2)
z_score

1.6448536269514722

In [19]:
margin_of_error=z_score*standard_error
margin_of_error

97.60003882151345

In [23]:
sample_mean=3486
sample_mean

3486

In [25]:
lower_bound=sample_mean-margin_of_error
upper_bound=sample_mean+margin_of_error
confidence_interval=np.array([lower_bound,upper_bound])
confidence_interval

array([3388.39996118, 3583.60003882])

In [27]:
CI=np.round(confidence_interval,decimals=2)
print(CI)

[3388.4 3583.6]


In [29]:
#Part-(b)
confidence_level=0.95
z_score=norm.ppf((1+confidence_level)/2)
z_score

1.959963984540054

In [31]:
margin_of_error=z_score*standard_error
margin_of_error

116.2976193416152

In [33]:
lower_bound=sample_mean-margin_of_error
upper_bound=sample_mean+margin_of_error
confidence_interval=np.array([lower_bound,upper_bound])
confidence_interval

array([3369.70238066, 3602.29761934])

In [35]:
CI=np.round(confidence_interval,decimals=2)
print(CI)

[3369.7 3602.3]


In [37]:
#Part-(c) 
confidence_level=0.99
z_score=norm.ppf((1+confidence_level)/2)
z_score

2.5758293035489004

In [39]:
margin_of_error=z_score*standard_error
margin_of_error

152.8409798322934

In [41]:
lower_bound=sample_mean-margin_of_error
upper_bound=sample_mean+margin_of_error
confidence_interval=np.array([lower_bound,upper_bound])
confidence_interval

array([3333.15902017, 3638.84097983])

In [43]:
CI=np.round(confidence_interval,decimals=2)
print(CI)

[3333.16 3638.84]
